---
- hosts: all

  become: yes
  become_user: root
  remote_user: deploy

  vars_files:
    - auth.yml
  vars:
    packages:
      - fail2ban
      - git
      - htop
      - nginx
      - nodejs
      - python-passlib
      - rethinkdb
      - sudo
      - ufw
      - vim

  tasks:
    # Install packages
    - name: Update system
      apt:
        update_cache: yes
        upgrade: safe
    - name: Install pip
      apt:
        name:
          - build-essential
          - python-dev
          - python-pip
    - name: Enable SNI support in Python 2.7.6
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - urllib3
        - pyopenssl
        - ndg-httpsclient
        - pyasn1
    - name: Add Nodesource key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: Add Nodesource repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_6.x trusty main
    - name: Add RethinkDB key
      apt_key:
        url: https://download.rethinkdb.com/apt/pubkey.gpg
    - name: Add RethinkDB repository
      apt_repository:
        repo: deb http://download.rethinkdb.com/apt trusty main
    - name: Add Nginx key
      apt_key:
        state: present
        url: https://nginx.org/keys/nginx_signing.key
    - name: Add Nginx repository
      apt_repository:
        repo: deb http://nginx.org/packages/ubuntu trusty nginx
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ packages }}"

    # Lock down access
    - name: Set up firewall
      ufw:
        policy: deny
        state: enabled
    - name: Allow SSH connections
      ufw:
        port: 22
        proto: tcp
        rule: allow
    - name: Allow HTTP connections
      ufw:
        port: 80
        proto: tcp
        rule: allow
    - name: Disable password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: PasswordAuthentication no
        regexp: ^#?PasswordAuthentication
      notify: Restart SSH
    - name: Disable root SSH access
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: PermitRootLogin no
        regexp: ^PermitRootLogin
      notify: Restart SSH

    # Configure RethinkDB
    - name: Transfer RethinkDB config
      copy:
        dest: /etc/rethinkdb/instances.d/rethinkdb.conf
        src: rethinkdb.conf
      notify: Restart RethinkDB
    - name: Ensure RethinkDB is started
      service:
        name: rethinkdb
        state: started

    # Configure Nginx
    - name: Set Nginx admin password
      htpasswd:
        name: admin
        password: "{{ admin_password }}"
        path: /etc/nginx/rethinkdb.htpasswd
    - name: Transfer Nginx config
      copy:
        dest: /etc/nginx/conf.d/rethinkdb.conf
        src: nginx.conf
      notify: Restart Nginx
    - name: Disable Nginx default site
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      notify: Restart Nginx

    # Install Horizon
    - name: Create horizon user
      user:
        name: horizon
        shell: /usr/sbin/nologin
    - name: Check out the Horizon repository
      git:
        dest: /home/horizon/horizon
        repo: https://github.com/btmills/horizon.git
        version: 5b91bf2d5db812f99841784d69f721573b52408e
    - name: Install Horizon
      command: npm link
      args:
        chdir: /home/horizon/horizon/cli
        creates: /usr/bin/hz

    # Set up Hacknight app
    - name: Copy scripts
      synchronize:
        dest: /home/horizon
        rsync_opts: --exclude 'node_modules'
        src: scripts
    - name: Install script dependencies
      npm:
        path: /home/horizon/scripts
    - name: Set RethinkDB admin password
      command: node set-admin-password.js {{ admin_password }}
      args:
        chdir: /home/horizon/scripts

    - name: Copy source files
      synchronize:
        dest: /home/horizon/
        src: hacknight
      tags:
        - schema
    - name: Apply horizon schema
      command: hz schema apply --rdb-password {{ admin_password }} .hz/schema.toml
      args:
        chdir: /home/horizon/hacknight
      tags:
        - schema
    - name: Install pm2 from npm
      npm:
        global: yes
        name: pm2
    - name: Start horizon
      command: pm2 start .hz/pm2.json
      args:
        chdir: /home/horizon/hacknight
    - name: Run pm2 on startup
      command: pm2 startup
      args:
        creates: /etc/init.d/pm2-init.sh
    - name: Run horizon on startup
      command: pm2 save
      args:
        creates: /root/.pm2/dump.pm2

    # Start services on boot
    - name: Start RethinkDB automatically on boot
      service:
        enabled: yes
        name: rethinkdb
    - name: Start Nginx automatically on boot
      service:
        enabled: yes
        name: nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
    - name: Restart RethinkDB
      service:
        name: rethinkdb
        state: restarted
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
