[collections.messages]
[[collections.messages.indexes]]
fields = [["timestamp"]]

[collections.clues]
[[collections.clues.indexes]]
fields = [["timestamp"]]

[collections.responses]
[[collections.responses.indexes]]
fields = [["clueId"],["timestamp"]]

[collections.scores]
[[collections.scores.indexes]]
fields = [["score"]]

[collections.users]

[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"

[groups.authenticated]

[groups.authenticated.rules.read_current_user]
template = "collection('users').find({ id: userId() })"

[groups.authenticated.rules.list_messages]
template = "collection('messages')"
[groups.authenticated.rules.store_messages]
template = "collection('messages').store({ id: any(), text: any(), timestamp: any(), userId: userId() })"

[groups.authenticated.rules.list_clues]
template = "collection('clues')"
[groups.authenticated.rules.store_responses]
template = "collection('responses').store({ response: any(), clueId: any(), timestamp: any(), userId: userId() })"
[groups.authenticated.rules.list_scores]
template = "collection('scores')"
